local group = AttachedLocations.getGroup("Human")

local function registerSet(prefix)
    group:getOrCreateLocation(prefix .. "Rifle"):setAttachmentName("sling_rifle")
    group:getOrCreateLocation(prefix .. "Rifle2"):setAttachmentName("sling_rifle2")
    group:getOrCreateLocation(prefix .. "Rifle3"):setAttachmentName("sling_rifle3")
    group:getOrCreateLocation(prefix .. "Rifle4"):setAttachmentName("sling_rifle4")
    group:getOrCreateLocation(prefix .. "Rifle5"):setAttachmentName("sling_rifle5")
    group:getOrCreateLocation(prefix .. "Rifle Back"):setAttachmentName("sling_rifleback")

    group:getOrCreateLocation(prefix .. "Weapon"):setAttachmentName("sling_weapon")
    group:getOrCreateLocation(prefix .. "Weapon2"):setAttachmentName("sling_weapon2")
    group:getOrCreateLocation(prefix .. "Weapon3"):setAttachmentName("sling_weapon3")
    group:getOrCreateLocation(prefix .. "Weapon4"):setAttachmentName("sling_weapon4")
    group:getOrCreateLocation(prefix .. "Weapon5"):setAttachmentName("sling_weapon5")
    group:getOrCreateLocation(prefix .. "Weapon Back"):setAttachmentName("sling_weaponback")

    group:getOrCreateLocation(prefix .. "Shovel"):setAttachmentName("sling_shovel")
    group:getOrCreateLocation(prefix .. "Shovel2"):setAttachmentName("sling_shovel2")
    group:getOrCreateLocation(prefix .. "Shovel3"):setAttachmentName("sling_shovel3")
    group:getOrCreateLocation(prefix .. "Shovel4"):setAttachmentName("sling_shovel4")
    group:getOrCreateLocation(prefix .. "Shovel5"):setAttachmentName("sling_shovel5")
    group:getOrCreateLocation(prefix .. "Shovel Back"):setAttachmentName("sling_shovelback")
end

registerSet("")
registerSet("Sling1")
registerSet("Sling2")
registerSet("Sling3")
registerSet("Sling4")

group:getOrCreateLocation("SlingRifleBag"):setAttachmentName("sling_riflebag")
group:getOrCreateLocation("SlingWeaponBag"):setAttachmentName("sling_weaponbag")
group:getOrCreateLocation("SlingBladeBag"):setAttachmentName("sling_bladebag")
group:getOrCreateLocation("SlingShovelBag"):setAttachmentName("sling_shovelbag")

group:getOrCreateLocation("Shovel On Back"):setAttachmentName("sling_shovelback")
group:getOrCreateLocation("Knife Sheath"):setAttachmentName("knife_sheath")
group:getOrCreateLocation("Rifle On Back2"):setAttachmentName("rifle_back2")
group:getOrCreateLocation("Blade On Back2"):setAttachmentName("blade_back2")

group:getOrCreateLocation("Chest Rig Mag Left"):setAttachmentName("chest_rig_mag_left")
group:getOrCreateLocation("Chest Rig Mag Right"):setAttachmentName("chest_rig_mag_right")
group:getOrCreateLocation("Chest Rig"):setAttachmentName("chest_rig")
group:getOrCreateLocation("Chest Rig Knife"):setAttachmentName("chest_rig_knife")
group:getOrCreateLocation("Chest Rig Gear"):setAttachmentName("chest_rig_gear")
group:getOrCreateLocation("Chest Rig Gear Right"):setAttachmentName("chest_rig_gear_right")
group:getOrCreateLocation("Chest Light"):setAttachmentName("chest_light")
group:getOrCreateLocation("Chest Light Right"):setAttachmentName("chest_light_right")
group:getOrCreateLocation("Chest Rig Walkie"):setAttachmentName("chest_rig_walkie")
group:getOrCreateLocation("Chest Rig Walkie Right"):setAttachmentName("chest_rig_walkie_right")
group:getOrCreateLocation("Chest Rig Bottle"):setAttachmentName("chest_rig_bottle")
group:getOrCreateLocation("Chest Rig Bottle Right"):setAttachmentName("chest_rig_bottle_right")
group:getOrCreateLocation("Gear Belt Right"):setAttachmentName("gear_belt_right")
group:getOrCreateLocation("Gear Belt Left"):setAttachmentName("gear_belt_left")
group:getOrCreateLocation("Claf in Sheath (Back)"):setAttachmentName("Knife_Sheath_Back")
group:getOrCreateLocation("Claf in Sheath (Leg)"):setAttachmentName("Knife_Sheath_Leg")
group:getOrCreateLocation("Katana in Sheath"):setAttachmentName("Katana_Sheath")
