-- Registries for Rifle Sling mod (API 42.13+)
ItemBodyLocation.register("jsling:slinga")
ItemBodyLocation.register("jsling:slingb")
ItemBodyLocation.register("jsling:hunkvest")
ItemBodyLocation.register("jsling:knifesheathback")
ItemBodyLocation.register("jsling:katanasheath")
ItemBodyLocation.register("jsling:back2")
ItemBodyLocation.register("jsling:back3")
ItemBodyLocation.register("jsling:chestrig")
ItemBodyLocation.register("jsling:torsorig")
ItemBodyLocation.register("jsling:backrig")
ItemBodyLocation.register("jsling:knifesheath")
ItemBodyLocation.register("jsling:bandolier")
